apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: coredns
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        reload
        loadbalance
    }
    compute.internal:53 {
      template ANY ANY {
        rcode NXDOMAIN
      }
    }
